ProductionPortal_Solb/Controllers/LFMeltShopController.cs
using BAL.Repositories;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionPortal_Solb.Controllers
{
    public class LFMeltShopController : Controller
    {
        LFMeltShopRepository repo;
        public LFMeltShopController()
        {
            repo = new LFMeltShopRepository();
        }
        // GET: LFMeltShop
        public ActionResult list()
        {
            var records = repo.GetAllRecord();
            return View(records);
        }
        public ActionResult add(int? id)
        {
            var Grade = repo.GetAllGrade();
            ViewBag.Grade = new SelectList(Grade, "GRADE_ID", "GRADE_ID");
            var Delay = repo.GetAllDelays();
            ViewBag.Delay = new SelectList(Delay, "GROUP_NAME", "GROUP_NAME");
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult add(LFMeltShopBLL model)
        {
            try
            {
                model.StatusID = 1;
                model.CreatedDate = DateTime.Now;
                model.CreatedBy = User.Identity.Name;
                int rtn = repo.InsertLF(model);
                if (model.Delays != null && model.Delays.Any())
                {
                    foreach (var delay in model.Delays)
                    {
                        repo.AddDelays(new DelaysBLL
                        {
                            HeatID = rtn,
                            HeatNo = model.HeatNo,
                            StatusID = 1,
                            CreatedDate = DateTime.Now,
                            CreatedBy = User.Identity.Name,
                            PlantID = 1,
                            PlantName = "LF Meltshop",
                            StartTime = delay.StartTime,
                            EndTime = delay.EndTime,
                            TotalDuration = delay.TotalDuration,
                            Reason = delay.Reason
                        });
                    }
                }
            }
            catch (Exception ex)
            {
            }
            return RedirectToAction("list");
        }
    }
}

ProductionPortal_Solb/Controllers/OtherController.cs
using BAL.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionPortal_Solb.Controllers
{
    public class OtherController : Controller
    {
        OtherRepository repo;
        public OtherController()
        {
            repo = new OtherRepository();
        }
        // GET: Other
        public ActionResult Delays()
        {
            var requests = repo.GetAllDelays();
            return View(requests);
        }
    }
}

ProductionPortal_Solb/Controllers/UserController.cs
using BAL.Repositories;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionPortal_Solb.Controllers
{
    public class UserController : Controller
    {
        UserRepository repo;
        UserRoleRepository role;
        public UserController()
        {
            repo = new UserRepository();
            role = new UserRoleRepository();
        }
        // GET: User
        public ActionResult list()
        {
            var data = repo.GetAll();
            return View(data);
        }
        [HttpGet]
        public ActionResult add(int? id)
        {
            var Role = role.GetAll();
            ViewBag.Role = new SelectList(Role, "ID", "RoleName");
            return View();
        }
        [HttpPost]
        public ActionResult Save(UserBLL data)
        {
            if (data.ID == 0 || data.ID == null)  // New record
            {
                data.CreatedDate = DateTime.Now;
                data.StatusID = 1;
                int result = repo.Insert(data);

                if (result > 0)
                {
                    TempData["Success"] = "Role saved successfully!";
                }
                else
                {
                    TempData["Error"] = "Failed to save the role.";
                }

                // redirect to list page (or to Add if you prefer)
                return RedirectToAction("list");
            }
            else  // Update
            {
                data.CreatedDate = DateTime.Now;

                ////int result = repo.Update(model);

                //if (result > 0)
                //{
                //    TempData["Success"] = "Role updated successfully!";
                //}
                //else
                //{
                //    TempData["Error"] = "Failed to update the role.";
                //}

                return RedirectToAction("list");
            }
        }
    }
}

ProductionPortal_Solb/Controllers/UserRoleController.cs
using BAL.Repositories;
using DAL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProductionPortal_Solb.Controllers
{
    public class UserRoleController : Controller
    {
        UserRoleRepository repo;
        public UserRoleController()
        {
            repo = new UserRoleRepository();
        }
        // GET: UserRole
        public ActionResult list()
        {
            var data = repo.GetAll();
            return View(data);
        }
        [HttpGet]
        public ActionResult add(int? id)
        {
            return View();
        }
        [HttpPost]
        public ActionResult Save(UserRoleBLL model)
        {
            if (model.ID == 0 || model.ID == null)  // New record
            {
                model.CreatedDate = DateTime.Now;
                model.StatusID = 1;
                int result = repo.Insert(model);

                if (result > 0)
                {
                    TempData["Success"] = "Role saved successfully!";
                }
                else
                {
                    TempData["Error"] = "Failed to save the role.";
                }

                // redirect to list page (or to Add if you prefer)
                return RedirectToAction("list");
            }
            else  // Update
            {
                model.CreatedDate = DateTime.Now;

                ////int result = repo.Update(model);

                //if (result > 0)
                //{
                //    TempData["Success"] = "Role updated successfully!";
                //}
                //else
                //{
                //    TempData["Error"] = "Failed to update the role.";
                //}

                return RedirectToAction("list");
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            int rtn = repo.Delete(id);
            return RedirectToAction("list");
        }
    }
}

ProductionPortal_Solb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Neon is a bootstrap, laravel & php admin dashboard template">
    <meta name="keywords" content="admin, admin dashboard, admin panel, admin template, admin theme, bootstrap 4, laravel, php, crm, analytics, responsive, sass support, ui kits, web app, clean design">
    <meta name="author" content="Themesbox17">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">

    <title>Production Portal - Solb Steel</title>

    <!-- Fevicon -->
    <link rel="shortcut icon" href="~/assets/images/favicon.png">

    <!-- Start CSS -->
    <!-- Chartist Chart CSS -->
    <link rel="stylesheet" href="~/assets/plugins/chartist-js/chartist.min.css">

    <!-- Switchery CSS -->
    <link href="~/assets/plugins/switchery/switchery.min.css" rel="stylesheet">
    <!-- Datepicker CSS -->
    <link href="~/assets/plugins/datepicker/datepicker.min.css" rel="stylesheet" type="text/css">

    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/icons.css" rel="stylesheet" type="text/css">
    <link href="~/assets/css/style.css" rel="stylesheet" type="text/css">
    <!-- End CSS -->
    <!-- DataTables CSS -->
    <link href="~/assets/plugins/datatables/dataTables.bootstrap4.min.css" rel="stylesheet" type="text/css" />
    <link href="~/assets/plugins/datatables/buttons.bootstrap4.min.css" rel="stylesheet" type="text/css" />

    <!-- Responsive Datatable CSS -->
    <link href="~/assets/plugins/datatables/responsive.bootstrap4.min.css" rel="stylesheet" type="text/css" />
</head>
<body class="xp-vertical">
    <!-- Search Modal -->
    <div class="modal search-modal fade" id="xpSearchModal" tabindex="-1" role="dialog" aria-labelledby="xpSearchModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="xp-searchbar">
                        <form>
                            <div class="input-group">
                                <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn" type="submit" id="button-addon2">GO</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Start XP Container -->
    <div id="xp-container">
        <!-- Start XP Topbar -->
        <div class="xp-topbar">

            <!-- Start XP Row -->
            <div class="row">

                <!-- Start XP Col -->
                <div class="col-2 col-md-1 col-lg-1 order-2 order-md-1 align-self-center">
                    <div class="xp-menubar">
                        <a class="xp-menu-hamburger" href="javascript:void();">
                            <i class="icon-menu font-20 text-white"></i>
                        </a>
                    </div>
                </div>
                <!-- End XP Col -->
                <!-- Start XP Col -->
                <div class="col-10 col-md-11 col-lg-11 order-1 order-md-2">
                    <div class="xp-profilebar text-right">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item mr-0">
                                <div class="dropdown xp-userprofile">
                                    @*<a class="dropdown-toggle" href="#" role="button" id="xp-userprofile" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="~/assets/images/topbar/user.jpg" alt="user-profile" class="rounded-circle img-fluid"><span class="xp-user-live"></span></a>*@
                                    <a class="dropdown-toggle py-3 text-white text-center font-18" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Welcome, @User.Identity.Name</a>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="xp-userprofile">
                                        @*<a class="dropdown-item py-3 text-white text-center font-16" href="#">Welcome, @User.Identity.Name</a>*@
                                        <a class="dropdown-item py-3" href="@Url.Action("Logout", "Login")"><i class="icon-power text-danger mr-2"></i> Logout</a>
                                    </div>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- End XP Col -->

            </div>
            <!-- End XP Row -->

        </div>
        <!-- End XP Topbar -->
        <!-- Start XP Leftbar -->
        <div class="xp-leftbar">

            <!-- Start XP Sidebar -->
            <div class="xp-sidebar">

                <!-- Start XP Logobar -->
                <div class="xp-logobar text-center">
                    <a href="@Url.Action("Index", "Home")" class="xp-logo"><img src="~/assets/images/logo.png" class="img-fluid" alt="logo" style="width:75%;"></a>
                </div>
                <!-- End XP Logobar -->
                <!-- Start XP Navigationbar -->
                <div class="xp-navigationbar">
                    <ul class="xp-vertical-menu">
                        <li class="xp-vertical-header">Main</li>
                        <li>
                            <a href="@Url.Action("Index", "Home")">
                                <i class="icon-speedometer"></i><span>Dashboard</span>
                            </a>
                        </li>
                        <li>
                            <a href="javaScript:void();">
                                <i class="icon-layers"></i><span>EAF MELTSHOP</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li><a href="@Url.Action("add", "EAFMeltShop")">Add Record</a></li>
                                <li><a href="@Url.Action("list", "EAFMeltShop")">View Record</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javaScript:void();">
                                <i class="icon-social-dropbox"></i><span>LF MELTSHOP</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li><a href="@Url.Action("add", "LFMeltShop")">Add Record</a></li>
                                <li><a href="@Url.Action("list", "LFMeltShop")">View Record</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javaScript:void();">
                                <i class="icon-social-vkontakte"></i><span>CCM MELTSHOP</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li><a href="@Url.Action("add", "CCM")">Add Record</a></li>
                                <li><a href="@Url.Action("list", "CCM")">View Record</a></li>
                            </ul>
                        </li>
                        <li class="xp-vertical-header">Extras</li>
                        <li>
                            <a href="javaScript:void();">
                                <i class="icon-lock"></i><span>Other Reports</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li><a href="@Url.Action("Delays", "Other")">Delays List</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="javaScript:void();">
                                <i class="icon-settings"></i><span>Setting</span><i class="icon-arrow-right pull-right"></i>
                            </a>
                            <ul class="xp-vertical-submenu">
                                <li><a href="@Url.Action("list", "UserRole")">User Role</a></li>
                                <li><a href="@Url.Action("list", "User")">User</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <!-- End XP Navigationbar -->

            </div>
            <!-- End XP Sidebar -->

        </div>
        <!-- End XP Leftbar -->
        <!-- Start XP Rightbar -->
        <div class="xp-rightbar">

            @RenderBody()

            <!-- Start XP Footerbar -->
            <div class="xp-footerbar">
                <footer class="footer">
                    <p class="mb-0">© 2025 Solb Steel - All Rights Reserved.</p>
                </footer>
            </div>
            <!-- End XP Footerbar -->

        </div>
        <!-- End XP Rightbar -->

    </div>
    <!-- End XP Container -->
    <!-- Start JS -->
    <script src="~/assets/js/jquery.min.js"></script>
    <script src="~/assets/js/popper.min.js"></script>
    <script src="~/assets/js/bootstrap.min.js"></script>
    <script src="~/assets/js/modernizr.min.js"></script>
    <script src="~/assets/js/detect.js"></script>
    <script src="~/assets/js/jquery.slimscroll.js"></script>
    <script src="~/assets/js/sidebar-menu.js"></script>

    <!-- Required Datatable JS -->
    <script src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/datatables/dataTables.bootstrap4.min.js"></script>

    <!-- Chartist Chart JS -->
    <script src="~/assets/plugins/chartist-js/chartist.min.js"></script>
    <script src="~/assets/plugins/chartist-js/chartist-plugin-tooltip.min.js"></script>

    <!-- To Do List JS -->
    <script src="~/assets/js/init/to-do-list-init.js"></script>

    <!-- Datepicker JS -->
    <script src="~/assets/plugins/datepicker/datepicker.min.js"></script>
    <script src="~/assets/plugins/datepicker/i18n/datepicker.en.js"></script>

    <!-- Dashboard JS -->
    <script src="~/assets/js/init/dashborad.js"></script>

    <!-- Main JS -->
    <script src="~/assets/js/main.js"></script>
    <!-- End JS -->
    <!-- Buttons Examples -->
    <script src="~/assets/plugins/datatables/dataTables.buttons.min.js"></script>
    <script src="~/assets/plugins/datatables/buttons.bootstrap4.min.js"></script>
    <script src="~/assets/plugins/datatables/jszip.min.js"></script>
    <script src="~/assets/plugins/datatables/pdfmake.min.js"></script>
    <script src="~/assets/plugins/datatables/vfs_fonts.js"></script>
    <script src="~/assets/plugins/datatables/buttons.html5.min.js"></script>
    <script src="~/assets/plugins/datatables/buttons.print.min.js"></script>
    <script src="~/assets/plugins/datatables/buttons.colVis.min.js"></script>

    <!-- Responsive Examples -->
    <script src="~/assets/plugins/datatables/dataTables.responsive.min.js"></script>
    <script src="~/assets/plugins/datatables/responsive.bootstrap4.min.js"></script>

    <!-- Datatable init JS -->
    <script src="~/assets/js/init/table-datatable-init.js"></script>

    <!-- Switchery js -->
    <script src="~/assets/plugins/switchery/switchery.min.js"></script>
    <script src="~/assets/js/init/switchery-init.js"></script>

</body>
</html>